# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Title', kernelModule='', kernelFunction='', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='Material parameters', layout='LAYOUT_FILL_X|LAYOUT_FILL_Y')
RsgComboBox(name='ComboBox_1', p='GroupBox_1', text='Material:', keyword='materialName', default='', comboType='MDB', repository='materials', rootText='Model:', rootKeyword='modelName', layout='VERTICAL')
RsgTabBook(name='TabBook_1', p='GroupBox_1', layout='0')
RsgTabItem(name='TabItem_4', p='TabBook_1', text='Tab')
RsgTable(p='TabItem_4', numRows=3, columnData=[('Properties', 'String', 140), ('Mean', 'Float', 100), ('Std', 'Float', 100)], showRowNumbers=True, showGrids=True, keyword='keyword04', popupFlags='AFXTable.POPUP_CUT|AFXTable.POPUP_COPY|AFXTable.POPUP_PASTE|AFXTable.POPUP_INSERT_ROW|AFXTable.POPUP_DELETE_ROW|AFXTable.POPUP_CLEAR_CONTENTS|AFXTable.POPUP_READ_FROM_FILE|AFXTable.POPUP_WRITE_TO_FILE')
dialogBox.show()