# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Title', kernelModule='materialfunc', kernelFunction='materialfunc', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgComboBox(name='ComboBox_3', p='DialogBox', text='Material:', keyword='materialName', default='', comboType='MDB', repository='materials', rootText='Model:', rootKeyword='modelName', layout='HORIZONTAL')
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='Material parameters', layout='LAYOUT_FILL_X')
RsgGroupBox(name='GroupBox_3', p='GroupBox_1', text='Density', layout='0')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='Mean', keyword='Density_mean', default='')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='COV  ', keyword='Density_cov', default='')
RsgGroupBox(name='GroupBox_2', p='GroupBox_1', text='E', layout='0')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=12, labelText='Mean', keyword='E_mean', default='')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=12, labelText='COV  ', keyword='E_cov', default='')
RsgTextField(p='DialogBox', fieldType='Integer', ncols=12, labelText='Jobs', keyword='job_nums', default='1')
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='sample file name', keyword='datafile_name', default='sample_data')
dialogBox.show()