# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Title', kernelModule='materialfunc', kernelFunction='materialfunc', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgComboBox(name='ComboBox_3', p='DialogBox', text='Material:', keyword='materialName', default='', comboType='MDB', repository='materials', rootText='Model:', rootKeyword='modelName', layout='HORIZONTAL')
RsgGroupBox(name='GroupBox_6', p='DialogBox', text='Distribution & Sample', layout='LAYOUT_FILL_X')
RsgCheckButton(p='GroupBox_6', text='Latin Hypercube Sampling', keyword='LHSindex', default=False)
RsgRadioButton(p='GroupBox_6', text='Uniform', keyword='Distribution', default=False)
RsgRadioButton(p='GroupBox_6', text='Normal', keyword='Distribution', default=True)
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='Material parameters', layout='0')
RsgTabBook(name='TabBook_1', p='GroupBox_1', layout='0')
RsgTabItem(name='TabItem_4', p='TabBook_1', text='Density')
RsgLabel(p='TabItem_4', text='tonne/mm^3', useBoldFont=True)
RsgTable(p='TabItem_4', numRows=3, columnData=[('Density', 'Float', 100), ('COV', 'Float', 100), ('TEMP', 'Float', 100)], showRowNumbers=True, showGrids=True, keyword='Density', popupFlags='AFXTable.POPUP_CUT|AFXTable.POPUP_COPY|AFXTable.POPUP_PASTE|AFXTable.POPUP_INSERT_ROW|AFXTable.POPUP_DELETE_ROW|AFXTable.POPUP_CLEAR_CONTENTS|AFXTable.POPUP_READ_FROM_FILE')
RsgTabItem(name='TabItem_1', p='TabBook_1', text='Elastic')
RsgLabel(p='TabItem_1', text='MPa', useBoldFont=True)
RsgTable(p='TabItem_1', numRows=3, columnData=[('Young modulus', 'Float', 100), ('COV', 'Float', 100), ('TEMP', 'Float', 100)], showRowNumbers=True, showGrids=True, keyword='Elastic', popupFlags='AFXTable.POPUP_CUT|AFXTable.POPUP_COPY|AFXTable.POPUP_PASTE|AFXTable.POPUP_INSERT_ROW|AFXTable.POPUP_DELETE_ROW|AFXTable.POPUP_CLEAR_CONTENTS|AFXTable.POPUP_READ_FROM_FILE')
RsgTabItem(name='TabItem_2', p='TabBook_1', text='Plastic')
RsgTable(p='TabItem_2', numRows=3, columnData=[('Yield Stress Zero Plastic Strain', 'Float', 100), ('C1', 'Float', 100), ('Gamma1', 'Float', 100), ('C2', 'Float', 100), ('Gamma2', 'Float', 100), ('C3', 'Float', 100), ('Gamma3', 'Float', 100), ('COV', 'Float', 100), ('TEMP', 'Float', 100)], showRowNumbers=True, showGrids=True, keyword='Plastic', popupFlags='AFXTable.POPUP_CUT|AFXTable.POPUP_COPY|AFXTable.POPUP_PASTE|AFXTable.POPUP_INSERT_ROW|AFXTable.POPUP_DELETE_ROW|AFXTable.POPUP_CLEAR_CONTENTS|AFXTable.POPUP_READ_FROM_FILE')
RsgTabItem(name='TabItem_3', p='TabBook_1', text='Creep')
RsgTable(p='TabItem_3', numRows=3, columnData=[('Power Law Multiplier', 'Float', 100), ('Eq Stress Order', 'Float', 100), ('Time Order', 'Float', 100), ('COV', 'Float', 100), ('TEMP', 'Float', 100)], showRowNumbers=True, showGrids=False, keyword='Creep', popupFlags='')
RsgTextField(p='DialogBox', fieldType='Integer', ncols=12, labelText='Job nums:', keyword='job_nums', default='1')
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='CPU nums:', keyword='cpu_nums', default='1')
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='Sample file saving name:', keyword='datafile_name', default='sample_data')
dialogBox.show()